coopengo/coog-helm-charts

flower/templates/deployment.yaml
=> flower: Restore command to run flower service properly

coog/templates/web/deployment.yaml
=> web: Change database from redis to mongo

coog/CHANGELOG.md, coog/templates/celery/deployment.yaml, coog/templates/celery/single.yaml, coog/templates/cron/deployment.yaml
=> celery: fix health check for celery 5.0

coog/templates/cron/deployment.yaml
=> CRON: Fix POD deployment command (add database)

coog/CHANGELOG.md, coog/templates/celery/daily_cron.yaml
=> daily: Increase number of failed jobs history count

coog/templates/gateway/deployment.yaml
Fixing [commit](https://github.com/coopengo/coog-portal/pull/943)
=>  gateway: fix default port

coog/Chart.yaml, coog/templates/api-identity-manager/deployment.yaml, coog/templates/api-identity-manager/secrets.yaml, coog/templates/api/deployment.yaml, coog/templates/api/secrets.yaml, coog/templates/batch/migquottosr_job.yaml, coog/templates/batch/secrets.yaml, coog/templates/celery/daily_cron.yaml, coog/templates/celery/deployment.yaml, coog/templates/celery/secrets.yaml, coog/templates/celery/single.yaml, coog/templates/coog/deployment.yaml, coog/templates/coog/secrets.yaml, coog/templates/cron/deployment.yaml, coog/templates/cron/secrets.yaml, coog/templates/customer-backend/deployment.yaml, coog/templates/customer-backend/secrets.yaml, coog/templates/gateway/deployment.yaml, coog/templates/gateway/secrets.yaml, coog/templates/web/deployment.yaml, coog/templates/web/secrets.yaml, coog/values.yaml, coog/values_secrets.yaml
=> init Kubernetes secrets

coog/templates/customer-frontend/deployment.yaml
customer_frontend: update command to force "serve" to use the specific port 5000
=> customer_frontend: update command to force "serve" to use port 5000

coog/values.yaml
=> libroconv: Increase CPU limit to 300m

.gitlab-ci.yml, coog/Chart.yaml, coog/README.md, coog/templates/app-b2c/ingress.yaml, coog/templates/coog/ingress.yaml, coog/templates/customer-backend/ingress.yaml, coog/templates/customer-frontend/ingress.yaml, coog/templates/gateway/ingress.yaml, coog/templates/paybox/ingress.yaml, coog/templates/portal/ingress.yaml, coog/templates/static/ingress.yaml, coog/templates/web/ingress.yaml
=> Manage apiVersion for ingress depending of kubernetes version

coog/templates/app-b2c/ingress.yaml, coog/templates/coog/ingress.yaml, coog/templates/customer-backend/ingress.yaml, coog/templates/customer-frontend/ingress.yaml, coog/templates/gateway/ingress.yaml, coog/templates/paybox/ingress.yaml, coog/templates/portal/ingress.yaml, coog/templates/static/ingress.yaml, coog/templates/web/ingress.yaml
Wrong indentation when using dashes in < else >
=> coog-helm-charts: Fix ingresses for k8s < 1.19 (coreye)

coog/values.yaml
=> chart: bump resources requests

coog/values.yaml
=> chart: bump resources requests (#51)

coog/templates/api-identity-manager/deployment.yaml, coog/templates/api/deployment.yaml, coog/values.yaml
=> api: add variable MONGO_IDENTITY_DB_NAME

coog/templates/api-identity-manager/deployment.yaml, coog/templates/api-identity-manager/secrets.yaml, coog/templates/api/deployment.yaml, coog/templates/api/secrets.yaml, coog/templates/gateway/deployment.yaml, coog/templates/gateway/secrets.yaml, coog/templates/web/deployment.yaml, coog/templates/web/secret.yaml, coog/values_secrets.yaml
Fix #PPOP-25
Related to #PPOP-24
=> coog-helm-chart : Handle mongodb URI for replicatset

coog/CHANGELOG.md, coog/templates/api/deployment.yaml
=> coog-api: COOG_DOCUMENT_TOKEN_SECRET variable added to the coog-api component

coog/CHANGELOG.md, coog/templates/configmap-backcore.yaml, coog/templates/secret-backcore.yaml, coog/test_chart_values.yaml, coog/tests/configmap-backcore_test.yaml, coog/tests/secret-backcore_test.yaml, coog/values.yaml, coog/values_secrets.yaml
=> Manage variables for migration tools

coog/values.yaml
=> coog-helm-chart: set default requests in values files to half of defaults limits

coog/templates/coog/deployment.yaml
=> Update coog command

coog/templates/celery/deployment-single.yaml
=> Chart: [2.14] correctif sur la gestion des resources de celery single

coog/templates/celery/deployment.yaml, coog/tests/celery/deployment_test.yaml
=> coog-celery: Move "resources" management from container to pod

coog/templates/celery/deployment.yaml
=> celery: Use celery_maintenance entry point

coog/templates/celery/deployment.yaml
=> celery: Update probes to use new hostname

coog/templates/configmap-backcore.yaml, coog/tests/configmap-backcore_test.yaml
=> BackCore: Add the TRYTOND_GATEWAY__URL variable with a value equal to the GATEWAY_URL variable

coog/templates/configmap-backcore.yaml, coog/tests/configmap-backcore_test.yaml
=> [BackCore] Link to gateway with service address

coog/templates/b2c/deployment.yaml, coog/tests/b2c/deployment_test.yaml, coog/values.yaml
=> independent activation of api2bc and app2bc

coog/templates/b2b/ingress.yaml, coog/templates/b2c/ingress.yaml, coog/templates/coog/ingress.yaml, coog/templates/customer-backend/ingress.yaml, coog/templates/customer-frontend/ingress.yaml, coog/templates/gateway/ingress.yaml, coog/templates/static/ingress.yaml, coog/tests/b2b/ingress_test.yaml, coog/tests/b2c/ingress_test.yaml, coog/tests/coog/ingress_test.yaml, coog/tests/customer-backend/ingress_test.yaml, coog/tests/customer-frontend/ingress_test.yaml, coog/tests/gateway/ingress_test.yaml, coog/tests/static/ingress_test.yaml
=> coog-helm-chart: Fix pathtype for K8S 1.30+ with nginx ingress controller

coog/tests/celery/deployment_test.yaml, coog/values.yaml
Fix #PTANG-95
MASTER - 25.14 - 24.41 - 24.14
=> Remove resource spec at pod level

coog/values.yaml
=> change repository from bitnami to bitnamilegacy
